config/routes.rb
Rails.application.routes.draw do
  resources :events, except: [:new, :edit]

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  belongs_to :person

  scope :for_today, ->() {
    where(["DATE(start_at) <= DATE(?) AND DATE(?) <= DATE(end_at)", Date.today, Date.today])
  }
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :invitations
  has_many :events, through: :invitations
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  has_many :comments
  has_many :tasks
  has_many :invitations
  has_many :persons

  def admin
  	has_role? :admin
  end
  alias_method :admin?, :admin

  def admin= value
  	if value == "0"
      remove_role :admin
    elsif value == "1"
      add_role :admin
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    render json: @events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    render json: @event
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    if @event.save
      render json: @event, status: :created, location: @event
    else
      render json: @event.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    if @event.update(params[:event])
      head :no_content
    else
      render json: @event.errors, status: :unprocessable_entity
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    head :no_content
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  #before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_invitation, only: [:edit, :update, :destroy]

  def index
  end

  def list
    render :json => Invitation.where("event_id=?", params[:event_id]).to_json(:include => :person)
  end

  def show
    @invitation = Invitation.find(params[:id])
  end

  def new
    @invitation = Invitation.new
    invitations_path
  end

  def create
      @invitation = Invitation.new(create_params)

    if @invitation.save
      redirect_to @invitation
    else
      render :new
    end
  end

  def operation
    if params[:oper] == "del"
      Invitation.destroy(params[:id])
    end

    render :json => "ok"
  end

  def edit
    @invitation = Invitation.find(params[:id])
    irvitation_path(@invitation)
  end

  def update
    @invitation= Invitation.find(params[:id])
   
  	if @invitation.update update_params
      redirect_to invitation_path, notice: "#{@invitation.name} updated"
    else
      render 'edit'
    end
  end

  def destroy
    #authorize @invitation
    name = @invitation.person.name
    @invitation.destroy
    redirect_to invitations_path, notice: "#{name} was removed"
  end


  private

  def set_invitation
    @invitation = Invitation.find params[:id]
  end

  def create_params
    params.require(:invitation).permit(*policy(Invitation).new_permitted_attrs)
  end

  def update_params
    params.require(:invitation).permit(*policy(Invitation).edit_permitted_attrs)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_person, only: [:edit, :update, :destroy]

  def index
  end

  def list
    render :json => Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
    @url = people_path
  end

  def create
      @person = Person.new(create_params)

    if @person.save
      redirect_to @person
    else
      render :new
    end
  end

  def edit
  @person = Person.find(params[:id])
  @url = person_path(@person)
  end

  def update
    @person= Person.find(params[:id])
   
  	if @person.update update_params
      redirect_to person_path, notice: "#{@person.name} updated"
    else
      render 'edit'
    end
  end

  def destroy
    #authorize @person

    @person.destroy
    redirect_to people_path, notice: "#{@person.name} was removed"
  end


  private

  def set_person
    @person = Person.find params[:id]
  end

  def create_params
    params.require(:person).permit(*policy(Person).new_permitted_attrs)
  end

  def update_params
    params.require(:person).permit(*policy(Person).edit_permitted_attrs)
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_person, only: [:edit, :update, :destroy]

  def index
    if params[:event_id].present?
      @persons = Event.find(params[:event_id]).persons
    else
      @persons = Person.all
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
    @url = persons_path
  end

  def create
      @person = Person.new(create_params)

    if @person.save
      redirect_to @person
    else
      render :new
    end
  end

  def edit
  @person = Person.find(params[:id])
  @url = person_path(@person)
  end

  def update
    @person= Person.find(params[:id])
   
  	if @person.update update_params
      redirect_to person_path, notice: "#{@person.name} updated"
    else
      render 'edit'
    end
  end

  def destroy
    authorize @person

    @person.destroy
    redirect_to persons_path, notice: "#{@person.name} was removed"
  end


  private

  def set_person
    @person = Person.find params[:id]
  end

  def create_params
    params.require(:person).permit(*policy(Person).new_permitted_attrs)
  end

  def update_params
    params.require(:person).permit(*policy(Person).edit_permitted_attrs)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_task, only: [:edit, :update, :destroy]

  def index
  end

  def list
    render :json => Task.all #.to_json(:include => :user)
  end

  def show
  	@task = Task.find(params[:id])
  end

  def new
   @task = current_user.tasks.build
  end

  def create
    @task = Task.new(create_params)

    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit
    authorize @task
  end

  def update
    authorize @task

     if @task.update  update_params
        redirect_to @task, notice: "#{@task.title} updated"
     else
        render 'edit'
     end
    end

  def destroy
    authorize @task

    @task.destroy
    redirect_to tasks_path, notice: "#{@task.name} was removed"
  end 


 private

    def set_task
      @task = Task.find params[:id]
    end

  def create_params
    params.require(:task).permit(*policy(Task).new_permitted_attrs)
  end

  def update_params
    params.require(:task).permit(*policy(@task).edit_permitted_attrs)
  end

end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/_side_bar.html.erb
<nav class="side-bar">
    <ul class="title-area">
        <li class="name">
            <h1>
                <%= link_to "EvenTool", root_path %>
            </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
    <section class="top-bar-section">
        <ul class="left">
            <li class="divider"></li>
            <li class="<%= current_page?(events_path) ? "active" : "" %>">
                <%= link_to Event.model_name.human(count: 2), events_path %>
                </li>

            <li class="divider"></li>

            <li>
            <%= link_to Invitation.model_name.human(count: 2), invitations_path %>
            </li>

            <li class="divider"></li>

            <li>
                <%= link_to Person.model_name.human(count: 2), people_path %>
            </li>

            <li class="divider"></li>

            <li>
                <%= link_to Task.model_name.human(count: 2), tasks_path %>
            </li>

            <li class="divider"></li>
        </ul>
    </section>
    <section class="top-bar-section">
        <ul class="right">
            <li class="divider"></li>
            <% if current_user %>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
        </ul>
    </section>
</nav>

app/views/application/_top_bar.html.erb
<nav class="top-bar">
    <ul class="title-area">
        <li class="name">
            <h1>
                <%= link_to "EvenTool", root_path %>
            </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
    <section class="top-bar-section">
        <ul class="left">
            <li class="divider"></li>
            <li class="<%= current_page?(events_path) ? "active" : "" %>">
                <%= link_to Event.model_name.human(count: 2), events_path %>
                </li>

            <li class="divider"></li>

            <li>
            <%= link_to Invitation.model_name.human(count: 2), invitations_path %>
            </li>

            <li class="divider"></li>

            <li>
                <%= link_to Person.model_name.human(count: 2), people_path %>
            </li>

            <li class="divider"></li>

            <li>
                <%= link_to Task.model_name.human(count: 2), tasks_path %>
            </li>

            <li class="divider"></li>
        </ul>
    </section>
    <section class="top-bar-section">
        <ul class="right">
            <li class="divider"></li>
            <% if current_user %>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
        </ul>
    </section>
</nav>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
    <% @event.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>

    <div class="row">
        <div class="large-8 columns">
            <%= f.label :name %>
            <%= f.text_field :name %>
        </div>
    </div>

    <div class="row">
        <div class="large-8 columns">
            <%= f.label :description %>
            <%= f.text_area  :description %>
        </div>
    </div>

    <div class="row">
        <div class="large-8 columns">
            <%= f.label :start_at %>
            <%= f.date_field :start_at %>
        </div>
    </div>


    <div class="row">
        <div class="large-8 columns">
            <%= f.label :end_at %>
            <%= f.date_field :end_at %>
        </div>
    </div>

    <%= f.submit t('.save'), class: 'round button' %>
<% end %>

app/views/events/edit.html.erb
<h1>
    Editing <%= @event.name %>
</h1>

<%= render partial: 'form' %>

app/views/events/index.html.erb
<div class="header">
  <h1>Eventos</h1>
</div>

<div class="content">

  <section id="data">
    <div id="toolbar_search"></div>
    <table id="events"></table>
  </section>

  <section class="options">
  <% if policy(Event).new? %>
    <%= link_to "Nuevo Evento", new_event_path, class: 'pure-button pure-button-primary' %>
  <% end %>
  </section>

</div>

<div id="invitations_dialog">
  <div id="event_invitations_toolbar_search"></div>
  <table id="event_invitations"></table>
  <button id="search" class="pure-button pure-button-primary">Buscar personas</button>
</div>

<div id="people_dialog">
  <div id="event_people_toolbar_search"></div>
  <table id="event_people"></table>
  <button id="invite" class="pure-button pure-button-primary">Invitar</button>
</div>

<div id="tasks_dialog"></div>

app/views/events/show.html.erb
<h1>
    <%= @event.name %>
</h1>
<p>
    <%= @event.description %>
</p>

<p>
    <b>Dates:</b>
    <%= l @event.start_at, format: :short %>
    -
    <%= l @event.end_at, format: :short %>
</p>

<ul><% @event.tasks.each do |task| %>
  <li>
    <strong><%= task.title %> </strong><br />
    <%= task.description %><br />
    Asignado a:<%= task.user.email %>
  </li>
    <% end %>
</ul>



<h2><%= Comment.model_name.human count: 2 %></h2>

<%= render partial: 'comment_form', locals: {event: @event} %>

<ul id="comments" class="no-bullet">
  <%= render partial: 'comment', collection: @event.comments %>
</ul>

app/views/invitations/_form.html.erb
<%= form_for @invitation do |f| %>
    <% @invitation.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>

<form>
  <fieldset>
    <legend>Add Person at Event</legend>

    <div class="row">
      <div class="large-8 columns">
         <%= f.label :Event %>
         <%= f.collection_select :person_id, Person.all, :id, :name %>
      </div>
    </div>

    <div class="row">
      <div class="large-8 columns">
         <%= f.label :Event %>
         <%= f.collection_select :event_id, Event.all, :id, :name %>
      </div>
    </div>

  </fieldset>
  <%= f.submit t('.save'), class: 'round button' %>
</form>




<% end %>

app/views/invitations/edit.html.erb
<h1>
    Editing <%= @invitation.name %>
</h1>

  <%= render partial: 'form' %>

app/views/invitations/index.html.erb
<div class="header">
  <h1>EventId | Invitations</h1>
</div>

<div class="content">

  <section id="data">
    <div id="toolbar_search"></div>
    <table id="invitations"></table>
  </section>

  <section class="options">
  <% if policy(Invitation).new? %>
    <%= link_to "Nueva Invitación", new_invitation_path, class: 'pure-button pure-button-primary' %>
  <% end %>
  </section>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "EvenTool" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if flash[:alert] %>
      <div class="alert-box radius" data-alert>
          <%= flash[:alert] %>
          <a class="close" href>x</a>
      </div>
    <% end %>

    <% if flash[:notice] %>
      <div class="alert-box success radius" data-alert>
          <%= flash[:notice] %>
          <a class="close" href>x</a>
      </div>
    <% end %>

  <div id="layout">
    <a href="#menu" id="menuLink" class="menu-link"><span></span></a>
    <div id="menu">
      <div class="pure-menu pure-menu-open">
        <a class="pure-menu-heading" href="">EvenTool</a>
        <ul>
            <li class="divider"></li>
            <li class="<%= current_page?(events_path) ? "active" : "" %>">
                <%= link_to Event.model_name.human(count: 2), events_path %>
            </li>

            <li class="divider"></li>

            <li>
            <%= link_to Invitation.model_name.human(count: 2), invitations_path %>
            </li>

            <li class="divider"></li>

            <li>
                <%= link_to Person.model_name.human(count: 2), people_path %>
            </li>

            <li class="divider"></li>

            <li>
                <%= link_to Task.model_name.human(count: 2), tasks_path %>
            </li>

            <li class="divider"></li>
        </ul>
      </div>
      <% if current_user %>
         <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
         <li><%= link_to "Log in", new_user_session_path %></li>
         <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </div>

    <div id="main">

      <%= yield %>

    </div>

  </div>
  <div class="footer">
  </div>

  <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for @person, url: @url do |f| %>
    <% @person.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>

    <div class="row">
        <div class="large-8 columns">
            <%= f.label :name %>
            <%= f.text_field :name %>
        </div>
    </div>

    <div class="row">
        <div class="large-8 columns">
            <%= f.label :title %>
            <%= f.text_area  :title %>
        </div>
    </div>

    <div class="row">
        <div class="large-8 columns">
            <%= f.label :address %>
            <%= f.text_area  :address %>
        </div>
    </div>

    <div class="row">
        <div class="large-8 columns">
            <%= f.label :phone %>
            <%= f.text_area  :phone %>
        </div>
    </div>

    <div class="row">
        <div class="large-8 columns">
            <%= f.label :email %>
            <%= f.text_area  :email %>
        </div>
    </div>

<<<<<<< HEAD
    <%= f.submit('Save', class: 'round button') %>
=======
   <%= f.submit('Save', class: 'round button') %>
>>>>>>> bb4f3d8aa4ae6d51976210e60d5d84e6c7e8e24d
<% end %>

app/views/people/edit.html.erb
<h1>
    Editing <%= @person.name %>
</h1>

  <%= render partial: 'form' %>

app/views/people/index.html.erb
<div class="header">
  <h1><%= Person.model_name.human(count: 2) %></h1>
</div>

<div class="content">

  <section id="data">
    <div id="toolbar_search"></div>
    <table id="people"></table>
  </section>

  <section class="options">
    <%= link_to t(".new_person"), new_person_path, class: 'pure-button pure-button-primary' %>
  </section>

</div>

app/views/people/new.html.erb
<h1><%= t '.header' %></h1>

<%= render partial: 'form' %>

app/views/people/show.html.erb
<h1>
    <%= @person.name %>
</h1>
<p>
    <%= @person.title %>
</p>

<p>
    <%= @person.address %>
</p>

<p>
    <%= @person.phone %>
</p>

<p>
    <%= @person.email %>
</p>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
      <% @task.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>

    <div class="row">
      <div class="large-8 columns">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    </div>

    <div class="row">
      <div class="large-8 columns">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>
    </div>

    <div class="row">
      <div class="large-8 columns">
         <%= f.label :event_id %>
         <%= f.text_field :event_id %>
      </div>
    </div>

    <div class="row">
      <div class="large-8 columns">
         <%= f.label :User %>
         <%= f.collection_select :user_id, User.all, :id, :email %>
      </div>
    </div>

    <%= f.submit t('.save'), class: 'round button' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>
    Editing <%= @task.title %>
</h1>

  <%= render partial: 'form' %>

app/views/tasks/index.html.erb
<div class="header">
  <h1>Tasks</h1>
</div>

<div class="content">

  <section id="data">
    <div id="toolbar_search"></div>
    <table id="tasks"></table>
  </section>

  <section class="options">
  <% if policy(Task).new? %>
    <%= link_to "Nueva Task", new_task_path, class: 'pure-button pure-button-primary' %>
  <% end %>
  </section>

</div>

app/views/tasks/new.html.erb
<h1><%= t '.header' %></h1>

<%= render partial: 'form' %>

app/views/tasks/show.html.erb
<% if @task.blank? %>
    <p>No task found.</p>
<% else %>
<h1>
    <%= @task.title %>
</h1>
<p>
    <%= @task.description %>
</p>

<p>
    <b>Dates:</b>
    <%= l @task.created_at, format: :short %>
    -
    <%= l @task.updated_at, format: :short %>
</p>
<ul><% @task.event.tasks.each do |task| %>
  <li>
    <strong><%= task.title %> </strong><br />
    <%= task.description %><br />
    Asignado a:<%= task.user.email %>
  </li>
    <% end %>
</ul>
<% end %>